-- Tablas sin FK

CREATE TABLE MoveCategory(
	MoveCategoryID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	DisplayName VARCHAR(30)
);

CREATE TABLE Type(
	TypeID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	DisplayName VARCHAR(30)
);

CREATE TABLE Abilty(
	AbilityID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	DisplayName VARCHAR(30),
	Effect VARCHAR(255)
);

CREATE TABLE EvolutionChain(
	EvolutionChainID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY
);

-- Tablas normales


-- Tablas intermedias (N:M)
